Repository bounswe/bounswe2023group2, pull requests merged in 2023-10, with the labels that each got.

#301 Lab Report 2
  reports/lab_report_2.md
Labels: team: all

#302 Delete .github/workflows/ci-cd.yml
  .github/workflows/ci-cd.yml
Labels: priority: low, required: feedback, effort: level 1, team: devops

#317 Mo/refactor/init project
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/.gitignore
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/.gitignore
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/build.gradle
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/proguard-rules.pro
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/androidTest/java/com/example/disasterresponseplatform/ExampleInstrumentedTest.kt
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/AndroidManifest.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/java/com/example/disasterresponseplatform/MainActivity.kt
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/drawable/ic_launcher_background.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/layout/activity_main.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/values-night/themes.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/values/colors.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/values/strings.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/values/themes.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/xml/backup_rules.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/main/res/xml/data_extraction_rules.xml
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/app/src/test/java/com/example/disasterresponseplatform/ExampleUnitTest.kt
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/build.gradle
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/gradle.properties
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/gradle/wrapper/gradle-wrapper.jar
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/gradle/wrapper/gradle-wrapper.properties
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/gradlew
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/gradlew.bat
  Disaster-Response-Platform/mobile/DisasterResponsePlatform/settings.gradle
Labels: effort: level 3, team: mobile

#353 use build instead of run dev
  Disaster-Response-Platform/frontend/Dockerfile
Labels: type: enhancement, effort: level 3, team: devops

#450 Be/test/authentication
  Disaster-Response-Platform/backend/Controllers/user_controller.py
  Disaster-Response-Platform/backend/Services/authentication_service.py
  Disaster-Response-Platform/backend/Tests/__init__.py
  Disaster-Response-Platform/backend/Tests/user_test.py
Labels: required: testing
