Repository bounswe/bounswe2023group2, pull requests merged in 2023-05, with the labels that each got.

#167 Create structure of practice-app
  practice-app/.gitignore
  practice-app/client/.eslintrc.json
  practice-app/client/README.md
  practice-app/client/next-env.d.ts
  practice-app/client/next.config.js
  practice-app/client/package.json
  practice-app/client/pages/_app.tsx
  practice-app/client/pages/_document.tsx
  practice-app/client/pages/alerts/index.tsx
  practice-app/client/pages/api/hello.ts
  practice-app/client/pages/index.tsx
  practice-app/client/pages/notifications/index.tsx
  practice-app/client/postcss.config.js
  practice-app/client/public/favicon.ico
  practice-app/client/public/next.svg
  practice-app/client/public/vercel.svg
  practice-app/client/styles/globals.css
  practice-app/client/tailwind.config.js
  practice-app/client/tsconfig.json
  practice-app/client/yarn.lock
  practice-app/server/README.md
  practice-app/server/__init__.py
  practice-app/server/main.py
  practice-app/server/requirements.txt
  practice-app/server/routers/__init__.py
  practice-app/server/routers/user.py
  practice-app/src/main.py
  practice-app/src/requirements.txt
Labels: state: assigned, priority: high, required: feedback, state: In progress, effort: level 1

#168 Cahid practice app
  practice-app/server/add_activity_api/.dockerignore
  practice-app/server/add_activity_api/.gitignore
  practice-app/server/add_activity_api/Dockerfile
  practice-app/server/add_activity_api/README.md
  practice-app/server/add_activity_api/const.py
  practice-app/server/add_activity_api/db.py
  practice-app/server/add_activity_api/db2.py
  practice-app/server/add_activity_api/main.py
  practice-app/server/add_activity_api/models.py
  practice-app/server/add_activity_api/run.sh
  practice-app/server/add_activity_api/start.sh
  practice-app/server/add_activity_api/templates/add_action.html
  practice-app/server/add_activity_api/templates/add_event.html
  practice-app/server/add_activity_api/templates/add_need.html
  practice-app/server/add_activity_api/templates/add_resource.html
  practice-app/server/add_activity_api/templates/delete_action.html
  practice-app/server/add_activity_api/templates/delete_event.html
  practice-app/server/add_activity_api/templates/delete_need.html
  practice-app/server/add_activity_api/templates/delete_resource.html
  practice-app/server/add_activity_api/templates/get_action.html
  practice-app/server/add_activity_api/templates/get_event.html
  practice-app/server/add_activity_api/templates/get_need.html
  practice-app/server/add_activity_api/templates/get_resource.html
  practice-app/server/add_activity_api/templates/index.html
  practice-app/server/add_activity_api/tests.py
  practice-app/server/database.sql
  practice-app/server/main.py
  practice-app/server/requirements.txt
Labels: type: enhancement, required: revision, priority: high, effort: level 3

#182 Add mongodb
  practice-app/server/config.example.py
  practice-app/server/config.py
  practice-app/server/database/__init__.py
  practice-app/server/database/baseSchema.py
  practice-app/server/database/mongo.py
  practice-app/server/database/userSchema.py
  practice-app/server/routers/user.py
Labels: required: feature, priority: high, required: feedback, effort: level 3

#214 Filter & Sort: External API Usage (Backend)
  practice-app/server/main.py
  practice-app/server/requirements.txt
  practice-app/server/routers/filtersort.py
Labels: priority: critical, required: feedback, state: In progress, effort: level 5

#193 Notifications
  practice-app/.gitignore
  practice-app/client/package.json
  practice-app/client/pages/notifications/index.tsx
  practice-app/client/public/firebase-messaging-sw.js
  practice-app/client/yarn.lock
  practice-app/server/config.example.py
  practice-app/server/database/userSchema.py
  practice-app/server/main.py
  practice-app/server/routers/notifications.py
Labels: required: feature, effort: level 9

#230 Closes #213
  practice-app/client/pages/notifications/index.tsx
  practice-app/server/routers/notifications.py
  practice-app/server/tests/test_notifications.py
Labels: effort: level 5
